package mops.foren.domain.model;

public enum Permission {
    CREATE_THREAD, READ_THREAD, DELETE_THREAD, READ_TOPIC, CREATE_TOPIC, DELETE_TOPIC, EDIT_TOPIC,
    CREATE_POST, DELETE_POST, EDIT_POST, READ_FORUM, MODERATE_THREAD
}
