= Teamdocumentation

Diese Dokumentation fixiert die während des Entwicklungsprozesses aufgetretenen Probleme und Lösungen, sowie die Entscheidungen die das Team in der Entwicklung getroffen hat.

[NOTE]
====
Constrains:

* Was für `Probleme` sind aufgetreten?
* Welche `Entscheidungen` wurden getroffen oder geändert?
Warum?
* Welche `Wochenziele` wurden gesetzt und wurden diese eingehalten.
====

== Probleme und Lösungen

=== Aufgabenteilung

====
Die Aufgabenaufteilung im Team bzw. in Teams von 2 Personen gestaltete sich schwierig.Oft kam es dazu, dass die Vorstellungen der konkreten Implementierungen, trotz der gleichen Idee sehr unterschiedlich waren.
Als das Projekt noch klein war, gab es zudem nicht genug unabhängige Baustellen für jedes Team.
====

* Wir haben stets versucht viel zu kommunizieren (teilweise zu viel), um Missverständnisse auszuräumen, Implementierungen zu fixieren und Aufgaben sinnvoll aufzuteilen.

=== Remote Praktikum

====
Die Verlegung des Praktikums ins `Home Office` führt zu Problemen in der Kommunikation und Koordination der Teams und somit zu einem Produktivitätsverlust.
====

* Mithilfe von Hangouts konnten wir einen neuen Workflow in unsere Arbeit integrieren und des Weiteren an getroffenen Reglements festhalten.
Es hat allerdings Zeit gekostet, bis sich die Teammitglieder auf die neue Arbeitsweise eingestellt haben.

=== Permission System

====
Es gab inhaltliche und softwaretechnische Diskrepanzen, wie und in welchem Umfang das Permission System implementiert werden soll.
Deshalb wurde die Software häufig diskutiert und geändert, ohne konkreten Mehrwert zu liefern.
====

* Wir haben uns entschieden das Permission System so spät wie möglich zu implementieren und dann an die Gegebenheiten des Domainmodel anzupassen.
Bis zur grundlegenden Implementierung des Domainmodels, gibt es bei uns nur den User `Studentin`.

=== Security/Keycloak

====
Die Einbindung und Konfiguration von sicherheitstechnischer Software in die Infrastruktur, sowie den Tests, insbesondere Keycloak hat allen Teammitglieder gleichermaßen Probleme bereitet.
Dies lag zum einen an der mangelnden Erfahrung mit Keycloak und zum anderen an dem ambivalenten Demoprojekt.
====

== Wochenziele

=== Woche 1

==== Ziel

* einheitliche `Konfiguration der IDE` sowie der CI
* Festlegen von `Regeln und Workflows` für das Team
* Einigung auf eine `Architektur sowie ein Model`, welches dann anschließend implementiert werden soll.
* Das Ziel konnte am Ende der Woche termingerecht erreicht werden, Fortschritt wurde in den Masterbranch integriert.

=== Woche 2

==== Ziel

* Integration eines ersten Spikes in das Projekt.
* Ein erster kleiner Workflow im Gesamtsystem sollte möglich sein.
* Das Ziel konnte nicht termingerecht erreicht werden.
Gründe dafür sind aus dem Kapitel `Probleme und Lösungen` zu entnehmen.

=== Woche 3

==== Ziel

* Integration der Anwendungslogik, sodass die ersten link:Documentation/userstories.adoc[Userstories] durchgeführt werden können.